name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python
  - jupyterlab
  - mlflow
  - numpy
  - cookiecutter
  - hydra-core
  - matplotlib
  - pandas
  - git
  - pip
  - pip:
      - wandb